services:
 db:
   image: postgres:latest
   environment:
     POSTGRES_USER: nattwut
     POSTGRES_PASSWORD: 12456
     POSTGRES_DB: nattwut
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
 adminer:
   image: adminer:latest
   ports:
     - "8080:8080"
   depends_on:
     - db
 
volumes:
  postgres_data: